### ISSUE TITLE
Need more examples....

### ISSUE THREAD

**Issue by ponymuch** [yj7/YJSoapEngine#2]
hey~
could you pls give some examples in the demo.
a url like this : "http://www.webservicex.net/globalweather.asmx?wsdl"
how to use the GetWeather in this url?

i have tried but get this information:

[__name: soap:Fault, faultstring: System.Web.Services.Protocols.SoapException: Server did not recognize the value of HTTP Header SOAPAction: GetWeather.
   at System.Web.Services.Protocols.Soap11ServerProtocolHelper.RouteRequest()
   at System.Web.Services.Protocols.SoapServerProtocol.RouteRequest(SoapServerMessage message)
   at System.Web.Services.Protocols.SoapServerProtocol.Initialize()
   at System.Web.Services.Protocols.ServerProtocolFactory.Create(Type type, HttpContext context, HttpRequest request, HttpResponse response, Boolean& abortProcessing), faultcode: soap:Client]

**Comment by yj7** [comment]
I added another method in the example project for the GetWeather soap Action of this service http://www.webservicex.net/globalweather.asmx

Cheers!
